name: build push and deploy image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE1}}


jobs:
  build:
    runs-on: ubuntu-latest  # github runner
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: AWS creds config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.AWS_ACTION_ROLE1}} # OIDC connect
          aws-region: ${{env.AWS_REGION}}
      - name: login to ecr
        uses: aws-actions/amazon-ecr-login@v1

